### PR TITLE
Minor workshop observations

### PR DESCRIPTION
**Pull request by nagaprabhu**

### CODE REVIEW

**Review by mfelsche — APPROVED** [review]
Great catches!

**Comment by mfelsche** [comment]
We just need you to sign-off your commits. See: https://github.com/tremor-rs/tremor-www-docs/pull/34/checks?check_run_id=1275377290

**Comment by nagaprabhu** [comment]
Signed-off.

**Comment by mfelsche** [comment]
Alex is slightly misconfigured, but all is good.

**Review by mfelsche — APPROVED** [review]

**Pull request merged**
