### PR TITLE
Sundry typo, grammar fixes, and style modifications for consistency

### PR DESCRIPTION
**Pull request by skoech**

### CODE REVIEW

**Review by Licenser — APPROVED** [review]
Thank you so much, this is huge! :rocket:

**Review by darach — APPROVED** [review]
Woo! LGTM!

**Comment by skoech** [comment]
No worries!

> Woo! LGTM!



> Thank you so much, this is huge! rocket

No worries!

**Comment by skoech** [comment]
> Woo! LGTM!

Cool!

**Comment by skoech** [comment]
> Thank you so much, this is huge! rocket

No worries!

**Pull request merged**
