### PR TITLE
Fix a lot of typos

### PR DESCRIPTION
**Pull request by marioortizmanero**
Hi there!

I'm trying to know more about Tremor for the GSoC projects and found a few typos in the docs. So I went ahead and did a manual review of the entire docs while I was at it. Let me know if any of these changes is wrong.

Also, not sure why the CI is failing.

### CODE REVIEW

**Review by mfelsche — APPROVED** [review]
Thank you!

**Comment by mfelsche** [comment]
TheCI alex job fails for forks in general, nothing to worry about

**Comment by darach** [comment]
Thank you Mario! 💯

**Comment by Licenser** [comment]
Thank you!!!

**Pull request merged**
